### ISSUE TITLE
Could be updated with these job boards

### ISSUE THREAD

**Issue by RayBB** [wfhio/awesome-job-boards#27]
There are a ton of job boards posted on this HN thread.
This repo could use some of the new ones posted here :)
https://news.ycombinator.com/item?id=14686745

**Comment by wfhio** [comment]
Hi @RayBB , I already added [Orca](https://orcahq.com/jobs) and [NinjaJobs](https://ninjajobs.org/) from that list!  Are there any others that you'd like to see?  I wanted to add [Unicorn Hunt](https://unicornhunt.io/) but it's not quite clear who this board is for.  It seems targeted at the UK (well, London predominantly), but there is the occasional job that falls outside of the UK entirely.

Thanks!

--Matt

**Comment by RayBB** [comment]
I haven't thoroughly looked through these sites but they were on the thread and not in your list.
https://remotefriendly.work/
https://www.latitude.work/
http://www.authenticjobs.com/
https://www.workshape.io/

You could also add a section for international but I imagine people who are interested in a specific area would probably be able to find the job boards specific to it.

**Comment by wfhio** [comment]
Hi @RayBB,

https://remotefriendly.work/ -- hardly any jobs, nothing unique about this board
https://www.latitude.work/ -- nice looking board but I don't know what it's for?
http://www.authenticjobs.com/ -- brilliant job board, this should be on our list!
https://www.workshape.io/ -- looks brilliant, but I can't really see any jobs without registering

I'll get Authentic Jobs added to the list!

--Matt

**Comment by wfhio** [comment]
Closing off, thanks for the links @RayBB !
